### ISSUE TITLE
Protocol error (Input.dispatchMouseEvent): Invalid parameters Failed to deserialize params.x - BINDINGS: double value expected

### ISSUE THREAD

**Issue by searchingforcode** [Xetera/ghost-cursor#66] opened 2022-08-25 13:47 UTC
![image](https://user-images.githubusercontent.com/1987330/186681790-79b94e80-0fa0-4c94-845f-0fa1062b9340.png)

This the problem i am facing on when i am running it on the ubuntu 20.04 headless. It works in windows in headless mode.

**Comment by searchingforcode** [comment] 2022-08-25 14:21
Its happening on 16.1.1 puppeteer version. Its not happening on 16.1.0.

**Comment by Niek** [comment] 2022-08-30 14:29
I can't reproduce this, can you please check with the latest v1.1.14?

**Comment by chrschae** [comment] 2022-09-17 14:12
i also get this error while using v1.1.14

**Comment by lublak** [comment] 2022-09-29 11:40
@Niek i have the same issue with 18.0.5 and ghost-cursor 1.1.15

**Comment by lublak** [comment] 2022-09-29 11:47
Full error:
```
Warning: could not move mouse, error message: ProtocolError: Protocol error (Input.dispatchMouseEvent): Invalid parameters Failed to deserialize params.x - BINDINGS: double value expected at position 38
```

**Comment by Niek** [comment] 2022-09-29 12:27
Anyone with a simple reproducible script so I can check? I still haven't encountered this issue in the wild.

**Comment by lublak** [comment] 2022-09-29 12:36
@Niek i created an example for you.
It depends on n8n:
```cmd
npm i n8n -g
n8n
```
```
async function test() {
  const browser = await puppeteer.launch({
    devtools: true,
  });
  const page = await browser.newPage();
  await page.goto(`http://localhost:5678/workflow`);
  await page.addStyleTag({content: '.el-loading-mask{display: none;}'});
  await page.waitForSelector('[data-name=Start]');
  const cursor = createCursor(page);
  await installMouseHelper(page);
  console.log('Settings');
  await page.waitForSelector('#side-menu ul[role="menubar"] li[role=menuitem]:nth-child(7)');
  console.log('Click Settings');
  await cursor.click('#side-menu ul[role="menubar"] li[role=menuitem]:nth-child(7)');
}

test();
```
https://github.com/n8n-io/n8n

**Comment by lublak** [comment] 2022-09-29 14:43
path returns an invalid vector array:

```
[
  { x: 0, y: 0 },     { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN }, { x: NaN, y: NaN },
  ... 1 more item
]
```
at this position: https://github.com/Xetera/ghost-cursor/blob/master/src/spoof.ts#L359

to is here: `{ x: 0, y: 0 } { x: NaN, y: NaN }`
destination is  `{ x: NaN, y: NaN }`
box is `{}`
options is `undefined`

**Comment by lublak** [comment] 2022-09-29 14:46
@Niek i think the issue is here: `box`
https://github.com/Xetera/ghost-cursor/blob/master/src/spoof.ts#L350

**Comment by Niek** [comment] 2022-10-11 08:49
I still can't replicate this, @lublak I had to change the selector to `li[class*="settingsSubmenu"]` but then it worked fine.

**Comment by jsdevtom** [comment] 2023-02-08 11:09
I believe the problem is when the element of the selector doesn't exist. There doesn't seem to be any explicit error handling for this case. Instead, box is `{}` and the calculations of the `x` and the `y` still go ahead - resulting in `NaN`.

**Comment by Demigod79** [comment] 2024-05-07 05:37
Get the fuck outta my computer you fucking bitches

**Comment by Niek** [comment] 2024-05-17 11:38
This should be resolved by 6de4f444142df963f2b86948cb86067153f3adc0 now that we fire our own `Input. dispatchMouseEvent()`.

**Closed by Niek** 2024-05-17 11:38 UTC
